### ISSUE TITLE
Add name


### ISSUE THREAD

**Issue by iscifacts** [jwoc-jgec/intro-to-git#29]
I want to add my name in readme file

**Comment by SoumyadeepOSD** [comment]
@iscifacts   
- fork the repo
- go to terminal type `git clone <your_forked_link>`
- open the folder into code editor and add your name
- go to terminal and type `git add .`
- and then type `git commit -m <your_msg>`
- create your own branch by typing `git checkout -b <your_branch_name>`
- and type `git remote add origin <your_forked_link>`
- at last type `git push origin <your_branch_name>`

you're done✔️
